trigger:
- main  # Trigger pipeline on commits to main branch

resources:
  repositories:
    - repository: self
      trigger: 
        branches:
          include:
          - main

pool:
  vmImage: 'ubuntu-latest'  # Use Ubuntu build agent

variables:
  # Container registry service connection established during pipeline creation
  azureSubscription: 'Azure for Students'
  subscriptionId: 'cffe2fd3-28d1-4a98-af5a-016b906ea148'
  azureContainerRegistry: 'group16acr.azurecr.io'
  imageRepository: 'lab4-group16'
  containerRegistry: 'group16acr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'group16acr-auth'
  
  # Web App for Container
  webAppName: 'webappgrp16'
  resourceGroupName: 'group16-resources'

stages:
- stage: Build
  displayName: 'Build and push container image'
  jobs:  
  - job: Build
    displayName: 'Build job'
    steps:
    - task: Docker@2
      displayName: 'Build and push container image'
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(containerRegistry)
        tags: |
          $(tag)
          latest

- stage: Deploy
  displayName: 'Deploy to Azure Web App'
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: 'Deploy job'
    steps:
    - task: AzureWebAppContainer@1
      displayName: 'Deploy Azure Web App for Container'
      inputs:
        azureSubscription: $(azureSubscription)
        appName: $(webAppName)
        resourceGroupName: $(resourceGroupName)
        containers: $(containerRegistry)/$(imageRepository):$(tag)
        appSettings: |
          WEBSITES_ENABLE_APP_SERVICE_STORAGE=false