trigger:
- main  # Trigger pipeline on commits to main branch

pool:
  vmImage: 'ubuntu-latest'  # Use Ubuntu build agent

variables:
  acrLoginServer: 'group16acr.azurecr.io'
  imageRepository: 'lab4-group16'
  tag: '$(Build.BuildId)'
  webAppName: 'Webappgrp16'
  # These are from the publish profile you shared
  publishUrl: 'webappgrp16-cwdqddeqesapa6eq.scm.northeurope-01.azurewebsites.net:443'

steps:
# Build and push Docker image
- script: |
    # Login to ACR
    echo $(acrPassword) | docker login $(acrLoginServer) -u $(acrUsername) --password-stdin
    
    # Build the docker image
    docker build -t $(acrLoginServer)/$(imageRepository):$(tag) .
    
    # Push to ACR
    docker push $(acrLoginServer)/$(imageRepository):$(tag)
  displayName: 'Build and push Docker image'

# Deploy using publish profile
- task: AzureWebAppContainer@1
  displayName: 'Deploy to Azure Web App'
  inputs:
    appName: $(webAppName)
    imageName: $(acrLoginServer)/$(imageRepository):$(tag)
    publishProfilePassword: $(publishProfilePassword)
    publishProfileUsername: '$(publishProfileUsername)'
    containerRegistryUrl: 'https://$(acrLoginServer)'
    containerRegistryUsername: $(acrUsername)
    containerRegistryPassword: $(acrPassword)
    connectionType: 'PublishProfile'