trigger:
- main  # Trigger pipeline on commits to main branch

pool:
  vmImage: 'ubuntu-latest'  # Use Ubuntu build agent

variables:
  # Azure details
  acrName: 'group16acr'
  acrLoginServer: 'group16acr.azurecr.io'
  imageRepository: 'lab4-group16'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  webAppName: 'webappgrp16'

stages:
- stage: Build
  displayName: 'Build and push container image'
  jobs:  
  - job: Build
    displayName: 'Build job'
    steps:
    - script: |
        # Login to ACR using credentials stored in pipeline variables
        echo $(acrPassword) | docker login $(acrLoginServer) -u $(acrUsername) --password-stdin
        
        # Build the docker image
        docker build -t $(acrLoginServer)/$(imageRepository):$(tag) -t $(acrLoginServer)/$(imageRepository):latest -f $(dockerfilePath) .
        
        # Push to ACR
        docker push $(acrLoginServer)/$(imageRepository):$(tag)
        docker push $(acrLoginServer)/$(imageRepository):latest
      displayName: 'Build and push to ACR'

- stage: Deploy
  displayName: 'Deploy to Azure Web App'
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: 'Deploy job'
    steps:
    - task: FileTransform@1
      inputs:
        folderPath: '$(System.DefaultWorkingDirectory)/**/*.PublishSettings'
        fileType: 'xml'
        targetFiles: '**/*.PublishSettings'
            
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'PublishProfile'
        PublishProfilePath: '$(System.DefaultWorkingDirectory)/**/*.PublishSettings'
        PublishProfilePassword: '$(publishProfilePassword)'
        appType: 'webAppContainer'
        WebAppName: '$(webAppName)'
        DockerNamespace: '$(acrLoginServer)'
        DockerRepository: '$(imageRepository)'
        DockerImageTag: '$(tag)'